name: eng
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ###
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.1
  flutter_dotenv: ^6.0.0
  flutter_markdown: ^0.7.7+1
  flutter_slidable: ^4.0.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  go_router: ^16.2.1
  dio: ^5.9.0
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/fonts/
  fonts:
    - family: w400
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
    - family: w500
      fonts:
        - asset: assets/fonts/Rubik-Medium.ttf
    - family: w600
      fonts:
        - asset: assets/fonts/Rubik-SemiBold.ttf
    - family: w700
      fonts:
        - asset: assets/fonts/Rubik-Bold.ttf
